// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: genesis.proto

package io.hycon;

public final class GenesisProto {
  private GenesisProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Block)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.BlockHeader header = 1;</code>
     */
    boolean hasHeader();
    /**
     * <code>.BlockHeader header = 1;</code>
     */
    io.hycon.GenesisProto.BlockHeader getHeader();
    /**
     * <code>.BlockHeader header = 1;</code>
     */
    io.hycon.GenesisProto.BlockHeaderOrBuilder getHeaderOrBuilder();

    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    java.util.List<io.hycon.GenesisProto.Tx> 
        getTxsList();
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    io.hycon.GenesisProto.Tx getTxs(int index);
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    int getTxsCount();
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    java.util.List<? extends io.hycon.GenesisProto.TxOrBuilder> 
        getTxsOrBuilderList();
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    io.hycon.GenesisProto.TxOrBuilder getTxsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Block}
   */
  public  static final class Block extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Block)
      BlockOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Block.newBuilder() to construct.
    private Block(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Block() {
      txs_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Block(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              io.hycon.GenesisProto.BlockHeader.Builder subBuilder = null;
              if (header_ != null) {
                subBuilder = header_.toBuilder();
              }
              header_ = input.readMessage(io.hycon.GenesisProto.BlockHeader.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(header_);
                header_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                txs_ = new java.util.ArrayList<io.hycon.GenesisProto.Tx>();
                mutable_bitField0_ |= 0x00000002;
              }
              txs_.add(
                  input.readMessage(io.hycon.GenesisProto.Tx.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          txs_ = java.util.Collections.unmodifiableList(txs_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hycon.GenesisProto.internal_static_Block_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hycon.GenesisProto.internal_static_Block_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hycon.GenesisProto.Block.class, io.hycon.GenesisProto.Block.Builder.class);
    }

    private int bitField0_;
    public static final int HEADER_FIELD_NUMBER = 1;
    private io.hycon.GenesisProto.BlockHeader header_;
    /**
     * <code>.BlockHeader header = 1;</code>
     */
    @Override
	public boolean hasHeader() {
      return header_ != null;
    }
    /**
     * <code>.BlockHeader header = 1;</code>
     */
    @Override
	public io.hycon.GenesisProto.BlockHeader getHeader() {
      return header_ == null ? io.hycon.GenesisProto.BlockHeader.getDefaultInstance() : header_;
    }
    /**
     * <code>.BlockHeader header = 1;</code>
     */
    @Override
	public io.hycon.GenesisProto.BlockHeaderOrBuilder getHeaderOrBuilder() {
      return getHeader();
    }

    public static final int TXS_FIELD_NUMBER = 3;
    private java.util.List<io.hycon.GenesisProto.Tx> txs_;
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    @Override
	public java.util.List<io.hycon.GenesisProto.Tx> getTxsList() {
      return txs_;
    }
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    @Override
	public java.util.List<? extends io.hycon.GenesisProto.TxOrBuilder> 
        getTxsOrBuilderList() {
      return txs_;
    }
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    @Override
	public int getTxsCount() {
      return txs_.size();
    }
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    @Override
	public io.hycon.GenesisProto.Tx getTxs(int index) {
      return txs_.get(index);
    }
    /**
     * <code>repeated .Tx txs = 3;</code>
     */
    @Override
	public io.hycon.GenesisProto.TxOrBuilder getTxsOrBuilder(
        int index) {
      return txs_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (header_ != null) {
        output.writeMessage(1, getHeader());
      }
      for (int i = 0; i < txs_.size(); i++) {
        output.writeMessage(3, txs_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
	public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (header_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeader());
      }
      for (int i = 0; i < txs_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, txs_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.hycon.GenesisProto.Block)) {
        return super.equals(obj);
      }
      io.hycon.GenesisProto.Block other = (io.hycon.GenesisProto.Block) obj;

      boolean result = true;
      result = result && (hasHeader() == other.hasHeader());
      if (hasHeader()) {
        result = result && getHeader()
            .equals(other.getHeader());
      }
      result = result && getTxsList()
          .equals(other.getTxsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHeader()) {
        hash = (37 * hash) + HEADER_FIELD_NUMBER;
        hash = (53 * hash) + getHeader().hashCode();
      }
      if (getTxsCount() > 0) {
        hash = (37 * hash) + TXS_FIELD_NUMBER;
        hash = (53 * hash) + getTxsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.hycon.GenesisProto.Block parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.Block parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Block parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.Block parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Block parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.Block parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Block parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.Block parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Block parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.Block parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Block parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.Block parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.hycon.GenesisProto.Block prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Block}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Block)
        io.hycon.GenesisProto.BlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hycon.GenesisProto.internal_static_Block_descriptor;
      }

      @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hycon.GenesisProto.internal_static_Block_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hycon.GenesisProto.Block.class, io.hycon.GenesisProto.Block.Builder.class);
      }

      // Construct using io.hycon.GenesisProto.Block.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTxsFieldBuilder();
        }
      }
      @Override
	public Builder clear() {
        super.clear();
        if (headerBuilder_ == null) {
          header_ = null;
        } else {
          header_ = null;
          headerBuilder_ = null;
        }
        if (txsBuilder_ == null) {
          txs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          txsBuilder_.clear();
        }
        return this;
      }

      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hycon.GenesisProto.internal_static_Block_descriptor;
      }

      @Override
	public io.hycon.GenesisProto.Block getDefaultInstanceForType() {
        return io.hycon.GenesisProto.Block.getDefaultInstance();
      }

      @Override
	public io.hycon.GenesisProto.Block build() {
        io.hycon.GenesisProto.Block result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
	public io.hycon.GenesisProto.Block buildPartial() {
        io.hycon.GenesisProto.Block result = new io.hycon.GenesisProto.Block(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (headerBuilder_ == null) {
          result.header_ = header_;
        } else {
          result.header_ = headerBuilder_.build();
        }
        if (txsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            txs_ = java.util.Collections.unmodifiableList(txs_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.txs_ = txs_;
        } else {
          result.txs_ = txsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @Override
	public Builder clone() {
        return super.clone();
      }
      @Override
	public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @Override
	public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
	public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
	public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
	public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hycon.GenesisProto.Block) {
          return mergeFrom((io.hycon.GenesisProto.Block)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hycon.GenesisProto.Block other) {
        if (other == io.hycon.GenesisProto.Block.getDefaultInstance()) return this;
        if (other.hasHeader()) {
          mergeHeader(other.getHeader());
        }
        if (txsBuilder_ == null) {
          if (!other.txs_.isEmpty()) {
            if (txs_.isEmpty()) {
              txs_ = other.txs_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureTxsIsMutable();
              txs_.addAll(other.txs_);
            }
            onChanged();
          }
        } else {
          if (!other.txs_.isEmpty()) {
            if (txsBuilder_.isEmpty()) {
              txsBuilder_.dispose();
              txsBuilder_ = null;
              txs_ = other.txs_;
              bitField0_ = (bitField0_ & ~0x00000002);
              txsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTxsFieldBuilder() : null;
            } else {
              txsBuilder_.addAllMessages(other.txs_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
	public final boolean isInitialized() {
        return true;
      }

      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hycon.GenesisProto.Block parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hycon.GenesisProto.Block) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private io.hycon.GenesisProto.BlockHeader header_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.hycon.GenesisProto.BlockHeader, io.hycon.GenesisProto.BlockHeader.Builder, io.hycon.GenesisProto.BlockHeaderOrBuilder> headerBuilder_;
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      @Override
	public boolean hasHeader() {
        return headerBuilder_ != null || header_ != null;
      }
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      @Override
	public io.hycon.GenesisProto.BlockHeader getHeader() {
        if (headerBuilder_ == null) {
          return header_ == null ? io.hycon.GenesisProto.BlockHeader.getDefaultInstance() : header_;
        } else {
          return headerBuilder_.getMessage();
        }
      }
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      public Builder setHeader(io.hycon.GenesisProto.BlockHeader value) {
        if (headerBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          header_ = value;
          onChanged();
        } else {
          headerBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      public Builder setHeader(
          io.hycon.GenesisProto.BlockHeader.Builder builderForValue) {
        if (headerBuilder_ == null) {
          header_ = builderForValue.build();
          onChanged();
        } else {
          headerBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      public Builder mergeHeader(io.hycon.GenesisProto.BlockHeader value) {
        if (headerBuilder_ == null) {
          if (header_ != null) {
            header_ =
              io.hycon.GenesisProto.BlockHeader.newBuilder(header_).mergeFrom(value).buildPartial();
          } else {
            header_ = value;
          }
          onChanged();
        } else {
          headerBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      public Builder clearHeader() {
        if (headerBuilder_ == null) {
          header_ = null;
          onChanged();
        } else {
          header_ = null;
          headerBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      public io.hycon.GenesisProto.BlockHeader.Builder getHeaderBuilder() {
        
        onChanged();
        return getHeaderFieldBuilder().getBuilder();
      }
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      @Override
	public io.hycon.GenesisProto.BlockHeaderOrBuilder getHeaderOrBuilder() {
        if (headerBuilder_ != null) {
          return headerBuilder_.getMessageOrBuilder();
        } else {
          return header_ == null ?
              io.hycon.GenesisProto.BlockHeader.getDefaultInstance() : header_;
        }
      }
      /**
       * <code>.BlockHeader header = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.hycon.GenesisProto.BlockHeader, io.hycon.GenesisProto.BlockHeader.Builder, io.hycon.GenesisProto.BlockHeaderOrBuilder> 
          getHeaderFieldBuilder() {
        if (headerBuilder_ == null) {
          headerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.hycon.GenesisProto.BlockHeader, io.hycon.GenesisProto.BlockHeader.Builder, io.hycon.GenesisProto.BlockHeaderOrBuilder>(
                  getHeader(),
                  getParentForChildren(),
                  isClean());
          header_ = null;
        }
        return headerBuilder_;
      }

      private java.util.List<io.hycon.GenesisProto.Tx> txs_ =
        java.util.Collections.emptyList();
      private void ensureTxsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          txs_ = new java.util.ArrayList<io.hycon.GenesisProto.Tx>(txs_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.hycon.GenesisProto.Tx, io.hycon.GenesisProto.Tx.Builder, io.hycon.GenesisProto.TxOrBuilder> txsBuilder_;

      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      @Override
	public java.util.List<io.hycon.GenesisProto.Tx> getTxsList() {
        if (txsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(txs_);
        } else {
          return txsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      @Override
	public int getTxsCount() {
        if (txsBuilder_ == null) {
          return txs_.size();
        } else {
          return txsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      @Override
	public io.hycon.GenesisProto.Tx getTxs(int index) {
        if (txsBuilder_ == null) {
          return txs_.get(index);
        } else {
          return txsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder setTxs(
          int index, io.hycon.GenesisProto.Tx value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.set(index, value);
          onChanged();
        } else {
          txsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder setTxs(
          int index, io.hycon.GenesisProto.Tx.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.set(index, builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder addTxs(io.hycon.GenesisProto.Tx value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.add(value);
          onChanged();
        } else {
          txsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder addTxs(
          int index, io.hycon.GenesisProto.Tx value) {
        if (txsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTxsIsMutable();
          txs_.add(index, value);
          onChanged();
        } else {
          txsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder addTxs(
          io.hycon.GenesisProto.Tx.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.add(builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder addTxs(
          int index, io.hycon.GenesisProto.Tx.Builder builderForValue) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.add(index, builderForValue.build());
          onChanged();
        } else {
          txsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder addAllTxs(
          java.lang.Iterable<? extends io.hycon.GenesisProto.Tx> values) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, txs_);
          onChanged();
        } else {
          txsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder clearTxs() {
        if (txsBuilder_ == null) {
          txs_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          txsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public Builder removeTxs(int index) {
        if (txsBuilder_ == null) {
          ensureTxsIsMutable();
          txs_.remove(index);
          onChanged();
        } else {
          txsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public io.hycon.GenesisProto.Tx.Builder getTxsBuilder(
          int index) {
        return getTxsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      @Override
	public io.hycon.GenesisProto.TxOrBuilder getTxsOrBuilder(
          int index) {
        if (txsBuilder_ == null) {
          return txs_.get(index);  } else {
          return txsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      @Override
	public java.util.List<? extends io.hycon.GenesisProto.TxOrBuilder> 
           getTxsOrBuilderList() {
        if (txsBuilder_ != null) {
          return txsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(txs_);
        }
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public io.hycon.GenesisProto.Tx.Builder addTxsBuilder() {
        return getTxsFieldBuilder().addBuilder(
            io.hycon.GenesisProto.Tx.getDefaultInstance());
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public io.hycon.GenesisProto.Tx.Builder addTxsBuilder(
          int index) {
        return getTxsFieldBuilder().addBuilder(
            index, io.hycon.GenesisProto.Tx.getDefaultInstance());
      }
      /**
       * <code>repeated .Tx txs = 3;</code>
       */
      public java.util.List<io.hycon.GenesisProto.Tx.Builder> 
           getTxsBuilderList() {
        return getTxsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.hycon.GenesisProto.Tx, io.hycon.GenesisProto.Tx.Builder, io.hycon.GenesisProto.TxOrBuilder> 
          getTxsFieldBuilder() {
        if (txsBuilder_ == null) {
          txsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.hycon.GenesisProto.Tx, io.hycon.GenesisProto.Tx.Builder, io.hycon.GenesisProto.TxOrBuilder>(
                  txs_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          txs_ = null;
        }
        return txsBuilder_;
      }
      @Override
	public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
	public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Block)
    }

    // @@protoc_insertion_point(class_scope:Block)
    private static final io.hycon.GenesisProto.Block DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.hycon.GenesisProto.Block();
    }

    public static io.hycon.GenesisProto.Block getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Block>
        PARSER = new com.google.protobuf.AbstractParser<Block>() {
      @Override
	public Block parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Block(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Block> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Block> getParserForType() {
      return PARSER;
    }

    @Override
	public io.hycon.GenesisProto.Block getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlockHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BlockHeader)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Hash
     * </pre>
     *
     * <code>bytes merkleRoot = 2;</code>
     */
    com.google.protobuf.ByteString getMerkleRoot();

    /**
     * <pre>
     *Hash
     * </pre>
     *
     * <code>bytes stateRoot = 3;</code>
     */
    com.google.protobuf.ByteString getStateRoot();

    /**
     * <code>int32 difficulty = 4;</code>
     */
    int getDifficulty();

    /**
     * <code>int64 timeStamp = 5;</code>
     */
    long getTimeStamp();
  }
  /**
   * Protobuf type {@code BlockHeader}
   */
  public  static final class BlockHeader extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BlockHeader)
      BlockHeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlockHeader.newBuilder() to construct.
    private BlockHeader(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockHeader() {
      merkleRoot_ = com.google.protobuf.ByteString.EMPTY;
      stateRoot_ = com.google.protobuf.ByteString.EMPTY;
      difficulty_ = 0;
      timeStamp_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockHeader(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {

              merkleRoot_ = input.readBytes();
              break;
            }
            case 26: {

              stateRoot_ = input.readBytes();
              break;
            }
            case 32: {

              difficulty_ = input.readInt32();
              break;
            }
            case 40: {

              timeStamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hycon.GenesisProto.internal_static_BlockHeader_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hycon.GenesisProto.internal_static_BlockHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hycon.GenesisProto.BlockHeader.class, io.hycon.GenesisProto.BlockHeader.Builder.class);
    }

    public static final int MERKLEROOT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString merkleRoot_;
    /**
     * <pre>
     *Hash
     * </pre>
     *
     * <code>bytes merkleRoot = 2;</code>
     */
    @Override
	public com.google.protobuf.ByteString getMerkleRoot() {
      return merkleRoot_;
    }

    public static final int STATEROOT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString stateRoot_;
    /**
     * <pre>
     *Hash
     * </pre>
     *
     * <code>bytes stateRoot = 3;</code>
     */
    @Override
	public com.google.protobuf.ByteString getStateRoot() {
      return stateRoot_;
    }

    public static final int DIFFICULTY_FIELD_NUMBER = 4;
    private int difficulty_;
    /**
     * <code>int32 difficulty = 4;</code>
     */
    @Override
	public int getDifficulty() {
      return difficulty_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timeStamp_;
    /**
     * <code>int64 timeStamp = 5;</code>
     */
    @Override
	public long getTimeStamp() {
      return timeStamp_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!merkleRoot_.isEmpty()) {
        output.writeBytes(2, merkleRoot_);
      }
      if (!stateRoot_.isEmpty()) {
        output.writeBytes(3, stateRoot_);
      }
      if (difficulty_ != 0) {
        output.writeInt32(4, difficulty_);
      }
      if (timeStamp_ != 0L) {
        output.writeInt64(5, timeStamp_);
      }
      unknownFields.writeTo(output);
    }

    @Override
	public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!merkleRoot_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, merkleRoot_);
      }
      if (!stateRoot_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, stateRoot_);
      }
      if (difficulty_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, difficulty_);
      }
      if (timeStamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, timeStamp_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.hycon.GenesisProto.BlockHeader)) {
        return super.equals(obj);
      }
      io.hycon.GenesisProto.BlockHeader other = (io.hycon.GenesisProto.BlockHeader) obj;

      boolean result = true;
      result = result && getMerkleRoot()
          .equals(other.getMerkleRoot());
      result = result && getStateRoot()
          .equals(other.getStateRoot());
      result = result && (getDifficulty()
          == other.getDifficulty());
      result = result && (getTimeStamp()
          == other.getTimeStamp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MERKLEROOT_FIELD_NUMBER;
      hash = (53 * hash) + getMerkleRoot().hashCode();
      hash = (37 * hash) + STATEROOT_FIELD_NUMBER;
      hash = (53 * hash) + getStateRoot().hashCode();
      hash = (37 * hash) + DIFFICULTY_FIELD_NUMBER;
      hash = (53 * hash) + getDifficulty();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeStamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.hycon.GenesisProto.BlockHeader parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hycon.GenesisProto.BlockHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.BlockHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.BlockHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.hycon.GenesisProto.BlockHeader prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BlockHeader}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BlockHeader)
        io.hycon.GenesisProto.BlockHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hycon.GenesisProto.internal_static_BlockHeader_descriptor;
      }

      @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hycon.GenesisProto.internal_static_BlockHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hycon.GenesisProto.BlockHeader.class, io.hycon.GenesisProto.BlockHeader.Builder.class);
      }

      // Construct using io.hycon.GenesisProto.BlockHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
	public Builder clear() {
        super.clear();
        merkleRoot_ = com.google.protobuf.ByteString.EMPTY;

        stateRoot_ = com.google.protobuf.ByteString.EMPTY;

        difficulty_ = 0;

        timeStamp_ = 0L;

        return this;
      }

      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hycon.GenesisProto.internal_static_BlockHeader_descriptor;
      }

      @Override
	public io.hycon.GenesisProto.BlockHeader getDefaultInstanceForType() {
        return io.hycon.GenesisProto.BlockHeader.getDefaultInstance();
      }

      @Override
	public io.hycon.GenesisProto.BlockHeader build() {
        io.hycon.GenesisProto.BlockHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
	public io.hycon.GenesisProto.BlockHeader buildPartial() {
        io.hycon.GenesisProto.BlockHeader result = new io.hycon.GenesisProto.BlockHeader(this);
        result.merkleRoot_ = merkleRoot_;
        result.stateRoot_ = stateRoot_;
        result.difficulty_ = difficulty_;
        result.timeStamp_ = timeStamp_;
        onBuilt();
        return result;
      }

      @Override
	public Builder clone() {
        return super.clone();
      }
      @Override
	public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @Override
	public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
	public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
	public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
	public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hycon.GenesisProto.BlockHeader) {
          return mergeFrom((io.hycon.GenesisProto.BlockHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hycon.GenesisProto.BlockHeader other) {
        if (other == io.hycon.GenesisProto.BlockHeader.getDefaultInstance()) return this;
        if (other.getMerkleRoot() != com.google.protobuf.ByteString.EMPTY) {
          setMerkleRoot(other.getMerkleRoot());
        }
        if (other.getStateRoot() != com.google.protobuf.ByteString.EMPTY) {
          setStateRoot(other.getStateRoot());
        }
        if (other.getDifficulty() != 0) {
          setDifficulty(other.getDifficulty());
        }
        if (other.getTimeStamp() != 0L) {
          setTimeStamp(other.getTimeStamp());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
	public final boolean isInitialized() {
        return true;
      }

      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hycon.GenesisProto.BlockHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hycon.GenesisProto.BlockHeader) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString merkleRoot_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *Hash
       * </pre>
       *
       * <code>bytes merkleRoot = 2;</code>
       */
      @Override
	public com.google.protobuf.ByteString getMerkleRoot() {
        return merkleRoot_;
      }
      /**
       * <pre>
       *Hash
       * </pre>
       *
       * <code>bytes merkleRoot = 2;</code>
       */
      public Builder setMerkleRoot(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        merkleRoot_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Hash
       * </pre>
       *
       * <code>bytes merkleRoot = 2;</code>
       */
      public Builder clearMerkleRoot() {
        
        merkleRoot_ = getDefaultInstance().getMerkleRoot();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString stateRoot_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *Hash
       * </pre>
       *
       * <code>bytes stateRoot = 3;</code>
       */
      @Override
	public com.google.protobuf.ByteString getStateRoot() {
        return stateRoot_;
      }
      /**
       * <pre>
       *Hash
       * </pre>
       *
       * <code>bytes stateRoot = 3;</code>
       */
      public Builder setStateRoot(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        stateRoot_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Hash
       * </pre>
       *
       * <code>bytes stateRoot = 3;</code>
       */
      public Builder clearStateRoot() {
        
        stateRoot_ = getDefaultInstance().getStateRoot();
        onChanged();
        return this;
      }

      private int difficulty_ ;
      /**
       * <code>int32 difficulty = 4;</code>
       */
      @Override
	public int getDifficulty() {
        return difficulty_;
      }
      /**
       * <code>int32 difficulty = 4;</code>
       */
      public Builder setDifficulty(int value) {
        
        difficulty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 difficulty = 4;</code>
       */
      public Builder clearDifficulty() {
        
        difficulty_ = 0;
        onChanged();
        return this;
      }

      private long timeStamp_ ;
      /**
       * <code>int64 timeStamp = 5;</code>
       */
      @Override
	public long getTimeStamp() {
        return timeStamp_;
      }
      /**
       * <code>int64 timeStamp = 5;</code>
       */
      public Builder setTimeStamp(long value) {
        
        timeStamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timeStamp = 5;</code>
       */
      public Builder clearTimeStamp() {
        
        timeStamp_ = 0L;
        onChanged();
        return this;
      }
      @Override
	public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
	public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BlockHeader)
    }

    // @@protoc_insertion_point(class_scope:BlockHeader)
    private static final io.hycon.GenesisProto.BlockHeader DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.hycon.GenesisProto.BlockHeader();
    }

    public static io.hycon.GenesisProto.BlockHeader getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockHeader>
        PARSER = new com.google.protobuf.AbstractParser<BlockHeader>() {
      @Override
	public BlockHeader parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BlockHeader(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockHeader> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockHeader> getParserForType() {
      return PARSER;
    }

    @Override
	public io.hycon.GenesisProto.BlockHeader getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Tx)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *Address
     * </pre>
     *
     * <code>bytes from = 1;</code>
     */
    com.google.protobuf.ByteString getFrom();

    /**
     * <pre>
     *Address
     * </pre>
     *
     * <code>bytes to = 2;</code>
     */
    com.google.protobuf.ByteString getTo();

    /**
     * <code>int64 amount = 3;</code>
     */
    long getAmount();

    /**
     * <code>int64 fee = 4;</code>
     */
    long getFee();

    /**
     * <code>int32 nonce = 5;</code>
     */
    int getNonce();

    /**
     * <code>bytes signature = 6;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>bool recovery = 7;</code>
     */
    boolean getRecovery();
  }
  /**
   * Protobuf type {@code Tx}
   */
  public  static final class Tx extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Tx)
      TxOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Tx.newBuilder() to construct.
    private Tx(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Tx() {
      from_ = com.google.protobuf.ByteString.EMPTY;
      to_ = com.google.protobuf.ByteString.EMPTY;
      amount_ = 0L;
      fee_ = 0L;
      nonce_ = 0;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      recovery_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Tx(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              from_ = input.readBytes();
              break;
            }
            case 18: {

              to_ = input.readBytes();
              break;
            }
            case 24: {

              amount_ = input.readInt64();
              break;
            }
            case 32: {

              fee_ = input.readInt64();
              break;
            }
            case 40: {

              nonce_ = input.readInt32();
              break;
            }
            case 50: {

              signature_ = input.readBytes();
              break;
            }
            case 56: {

              recovery_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.hycon.GenesisProto.internal_static_Tx_descriptor;
    }

    @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.hycon.GenesisProto.internal_static_Tx_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.hycon.GenesisProto.Tx.class, io.hycon.GenesisProto.Tx.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString from_;
    /**
     * <pre>
     *Address
     * </pre>
     *
     * <code>bytes from = 1;</code>
     */
    @Override
	public com.google.protobuf.ByteString getFrom() {
      return from_;
    }

    public static final int TO_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString to_;
    /**
     * <pre>
     *Address
     * </pre>
     *
     * <code>bytes to = 2;</code>
     */
    @Override
	public com.google.protobuf.ByteString getTo() {
      return to_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 3;
    private long amount_;
    /**
     * <code>int64 amount = 3;</code>
     */
    @Override
	public long getAmount() {
      return amount_;
    }

    public static final int FEE_FIELD_NUMBER = 4;
    private long fee_;
    /**
     * <code>int64 fee = 4;</code>
     */
    @Override
	public long getFee() {
      return fee_;
    }

    public static final int NONCE_FIELD_NUMBER = 5;
    private int nonce_;
    /**
     * <code>int32 nonce = 5;</code>
     */
    @Override
	public int getNonce() {
      return nonce_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes signature = 6;</code>
     */
    @Override
	public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int RECOVERY_FIELD_NUMBER = 7;
    private boolean recovery_;
    /**
     * <code>bool recovery = 7;</code>
     */
    @Override
	public boolean getRecovery() {
      return recovery_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
	public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
	public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!from_.isEmpty()) {
        output.writeBytes(1, from_);
      }
      if (!to_.isEmpty()) {
        output.writeBytes(2, to_);
      }
      if (amount_ != 0L) {
        output.writeInt64(3, amount_);
      }
      if (fee_ != 0L) {
        output.writeInt64(4, fee_);
      }
      if (nonce_ != 0) {
        output.writeInt32(5, nonce_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(6, signature_);
      }
      if (recovery_ != false) {
        output.writeBool(7, recovery_);
      }
      unknownFields.writeTo(output);
    }

    @Override
	public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!from_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, from_);
      }
      if (!to_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, to_);
      }
      if (amount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, amount_);
      }
      if (fee_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, fee_);
      }
      if (nonce_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, nonce_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, signature_);
      }
      if (recovery_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, recovery_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.hycon.GenesisProto.Tx)) {
        return super.equals(obj);
      }
      io.hycon.GenesisProto.Tx other = (io.hycon.GenesisProto.Tx) obj;

      boolean result = true;
      result = result && getFrom()
          .equals(other.getFrom());
      result = result && getTo()
          .equals(other.getTo());
      result = result && (getAmount()
          == other.getAmount());
      result = result && (getFee()
          == other.getFee());
      result = result && (getNonce()
          == other.getNonce());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && (getRecovery()
          == other.getRecovery());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FROM_FIELD_NUMBER;
      hash = (53 * hash) + getFrom().hashCode();
      hash = (37 * hash) + TO_FIELD_NUMBER;
      hash = (53 * hash) + getTo().hashCode();
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getAmount());
      hash = (37 * hash) + FEE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFee());
      hash = (37 * hash) + NONCE_FIELD_NUMBER;
      hash = (53 * hash) + getNonce();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + RECOVERY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getRecovery());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.hycon.GenesisProto.Tx parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Tx parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.Tx parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.hycon.GenesisProto.Tx parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
	public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.hycon.GenesisProto.Tx prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
	public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Tx}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Tx)
        io.hycon.GenesisProto.TxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.hycon.GenesisProto.internal_static_Tx_descriptor;
      }

      @Override
	protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.hycon.GenesisProto.internal_static_Tx_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.hycon.GenesisProto.Tx.class, io.hycon.GenesisProto.Tx.Builder.class);
      }

      // Construct using io.hycon.GenesisProto.Tx.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
	public Builder clear() {
        super.clear();
        from_ = com.google.protobuf.ByteString.EMPTY;

        to_ = com.google.protobuf.ByteString.EMPTY;

        amount_ = 0L;

        fee_ = 0L;

        nonce_ = 0;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        recovery_ = false;

        return this;
      }

      @Override
	public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.hycon.GenesisProto.internal_static_Tx_descriptor;
      }

      @Override
	public io.hycon.GenesisProto.Tx getDefaultInstanceForType() {
        return io.hycon.GenesisProto.Tx.getDefaultInstance();
      }

      @Override
	public io.hycon.GenesisProto.Tx build() {
        io.hycon.GenesisProto.Tx result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
	public io.hycon.GenesisProto.Tx buildPartial() {
        io.hycon.GenesisProto.Tx result = new io.hycon.GenesisProto.Tx(this);
        result.from_ = from_;
        result.to_ = to_;
        result.amount_ = amount_;
        result.fee_ = fee_;
        result.nonce_ = nonce_;
        result.signature_ = signature_;
        result.recovery_ = recovery_;
        onBuilt();
        return result;
      }

      @Override
	public Builder clone() {
        return super.clone();
      }
      @Override
	public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @Override
	public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
	public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
	public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
	public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
	public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.hycon.GenesisProto.Tx) {
          return mergeFrom((io.hycon.GenesisProto.Tx)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.hycon.GenesisProto.Tx other) {
        if (other == io.hycon.GenesisProto.Tx.getDefaultInstance()) return this;
        if (other.getFrom() != com.google.protobuf.ByteString.EMPTY) {
          setFrom(other.getFrom());
        }
        if (other.getTo() != com.google.protobuf.ByteString.EMPTY) {
          setTo(other.getTo());
        }
        if (other.getAmount() != 0L) {
          setAmount(other.getAmount());
        }
        if (other.getFee() != 0L) {
          setFee(other.getFee());
        }
        if (other.getNonce() != 0) {
          setNonce(other.getNonce());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (other.getRecovery() != false) {
          setRecovery(other.getRecovery());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
	public final boolean isInitialized() {
        return true;
      }

      @Override
	public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.hycon.GenesisProto.Tx parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.hycon.GenesisProto.Tx) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString from_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes from = 1;</code>
       */
      @Override
	public com.google.protobuf.ByteString getFrom() {
        return from_;
      }
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes from = 1;</code>
       */
      public Builder setFrom(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        from_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes from = 1;</code>
       */
      public Builder clearFrom() {
        
        from_ = getDefaultInstance().getFrom();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString to_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes to = 2;</code>
       */
      @Override
	public com.google.protobuf.ByteString getTo() {
        return to_;
      }
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes to = 2;</code>
       */
      public Builder setTo(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        to_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *Address
       * </pre>
       *
       * <code>bytes to = 2;</code>
       */
      public Builder clearTo() {
        
        to_ = getDefaultInstance().getTo();
        onChanged();
        return this;
      }

      private long amount_ ;
      /**
       * <code>int64 amount = 3;</code>
       */
      @Override
	public long getAmount() {
        return amount_;
      }
      /**
       * <code>int64 amount = 3;</code>
       */
      public Builder setAmount(long value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 amount = 3;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0L;
        onChanged();
        return this;
      }

      private long fee_ ;
      /**
       * <code>int64 fee = 4;</code>
       */
      @Override
	public long getFee() {
        return fee_;
      }
      /**
       * <code>int64 fee = 4;</code>
       */
      public Builder setFee(long value) {
        
        fee_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 fee = 4;</code>
       */
      public Builder clearFee() {
        
        fee_ = 0L;
        onChanged();
        return this;
      }

      private int nonce_ ;
      /**
       * <code>int32 nonce = 5;</code>
       */
      @Override
	public int getNonce() {
        return nonce_;
      }
      /**
       * <code>int32 nonce = 5;</code>
       */
      public Builder setNonce(int value) {
        
        nonce_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nonce = 5;</code>
       */
      public Builder clearNonce() {
        
        nonce_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes signature = 6;</code>
       */
      @Override
	public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes signature = 6;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes signature = 6;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private boolean recovery_ ;
      /**
       * <code>bool recovery = 7;</code>
       */
      @Override
	public boolean getRecovery() {
        return recovery_;
      }
      /**
       * <code>bool recovery = 7;</code>
       */
      public Builder setRecovery(boolean value) {
        
        recovery_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool recovery = 7;</code>
       */
      public Builder clearRecovery() {
        
        recovery_ = false;
        onChanged();
        return this;
      }
      @Override
	public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
	public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Tx)
    }

    // @@protoc_insertion_point(class_scope:Tx)
    private static final io.hycon.GenesisProto.Tx DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.hycon.GenesisProto.Tx();
    }

    public static io.hycon.GenesisProto.Tx getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Tx>
        PARSER = new com.google.protobuf.AbstractParser<Tx>() {
      @Override
	public Tx parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Tx(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Tx> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Tx> getParserForType() {
      return PARSER;
    }

    @Override
	public io.hycon.GenesisProto.Tx getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Block_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Block_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BlockHeader_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BlockHeader_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Tx_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Tx_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rgenesis.proto\"=\n\005Block\022\034\n\006header\030\001 \001(\013" +
      "2\014.BlockHeader\022\020\n\003txs\030\003 \003(\0132\003.TxJ\004\010\002\020\003\"g" +
      "\n\013BlockHeader\022\022\n\nmerkleRoot\030\002 \001(\014\022\021\n\tsta" +
      "teRoot\030\003 \001(\014\022\022\n\ndifficulty\030\004 \001(\005\022\021\n\ttime" +
      "Stamp\030\005 \001(\003J\004\010\001\020\002J\004\010\006\020\007\"o\n\002Tx\022\014\n\004from\030\001 " +
      "\001(\014\022\n\n\002to\030\002 \001(\014\022\016\n\006amount\030\003 \001(\003\022\013\n\003fee\030\004" +
      " \001(\003\022\r\n\005nonce\030\005 \001(\005\022\021\n\tsignature\030\006 \001(\014\022\020" +
      "\n\010recovery\030\007 \001(\010B\030\n\010io.hyconB\014GenesisPro" +
      "tob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          @Override
		public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Block_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Block_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Block_descriptor,
        new java.lang.String[] { "Header", "Txs", });
    internal_static_BlockHeader_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_BlockHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BlockHeader_descriptor,
        new java.lang.String[] { "MerkleRoot", "StateRoot", "Difficulty", "TimeStamp", });
    internal_static_Tx_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Tx_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Tx_descriptor,
        new java.lang.String[] { "From", "To", "Amount", "Fee", "Nonce", "Signature", "Recovery", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
